# Generated by Django 3.1.7 on 2021-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_shopuser_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
